# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7fec68bfd75a7e5409205e0c0b65a26e67ef94d91c90a619b967f81da7d47eee4bca6465d226645eec95ef34b8d08181d6622af3d211995bc881ea34344ca5b

test:
  secret_key_base: b7e92608b94343d86c5b5b7e0e1b82b3b608e0ab15fc96ce225668b5a1f672829a93348f69de726d4b0918d57e22acd765e63d9c2acf2d5f441d0a4bb877bf17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
