source 'https://rubygems.org'


gem 'rails', '4.2.0'

gem 'rails-api'

gem 'spring', :group => :development
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'resque'

gem 'pg'
gem 'dotenv'


# To use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'
gem 'soundcloud'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
